// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pokemon.Models
{
    public partial class Eventos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public DateTime? Fecha { get; set; }
        public string Descripcion { get; set; }
        public int? GeneracionId { get; set; }

        public virtual Generaciones Generacion { get; set; }
    }
}