// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pokemon.Models
{
    public partial class Generaciones
    {
        public Generaciones()
        {
            Eventos = new HashSet<Eventos>();
            Pokemon = new HashSet<Pokemon>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Eventos> Eventos { get; set; }
        public virtual ICollection<Pokemon> Pokemon { get; set; }
    }
}