// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pokemon.Models
{
    public partial class Habilidades
    {
        public Habilidades()
        {
            PokemonHabilidad1 = new HashSet<Pokemon>();
            PokemonHabilidad2 = new HashSet<Pokemon>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Pokemon> PokemonHabilidad1 { get; set; }
        public virtual ICollection<Pokemon> PokemonHabilidad2 { get; set; }
    }
}