// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pokemon.Models
{
    public partial class Movimientos
    {
        public Movimientos()
        {
            PokemonMovimiento1 = new HashSet<Pokemon>();
            PokemonMovimiento2 = new HashSet<Pokemon>();
            PokemonMovimiento3 = new HashSet<Pokemon>();
            PokemonMovimiento4 = new HashSet<Pokemon>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public int? TipoId { get; set; }

        public virtual Tipos Tipo { get; set; }
        public virtual ICollection<Pokemon> PokemonMovimiento1 { get; set; }
        public virtual ICollection<Pokemon> PokemonMovimiento2 { get; set; }
        public virtual ICollection<Pokemon> PokemonMovimiento3 { get; set; }
        public virtual ICollection<Pokemon> PokemonMovimiento4 { get; set; }
    }
}