// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pokemon.Models
{
    public partial class Pokemon
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int? GeneracionId { get; set; }
        public int? Tipo1Id { get; set; }
        public int? Tipo2Id { get; set; }
        public int? Habilidad1Id { get; set; }
        public int? Habilidad2Id { get; set; }
        public int? Movimiento1Id { get; set; }
        public int? Movimiento2Id { get; set; }
        public int? Movimiento3Id { get; set; }
        public int? Movimiento4Id { get; set; }
        public string Imagen { get; set; }

        public virtual Generaciones Generacion { get; set; }
        public virtual Habilidades Habilidad1 { get; set; }
        public virtual Habilidades Habilidad2 { get; set; }
        public virtual Movimientos Movimiento1 { get; set; }
        public virtual Movimientos Movimiento2 { get; set; }
        public virtual Movimientos Movimiento3 { get; set; }
        public virtual Movimientos Movimiento4 { get; set; }
        public virtual Tipos Tipo1 { get; set; }
        public virtual Tipos Tipo2 { get; set; }
    }
}