// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pokemon.Models
{
    public partial class Tipos
    {
        public Tipos()
        {
            Movimientos = new HashSet<Movimientos>();
            PokemonTipo1 = new HashSet<Pokemon>();
            PokemonTipo2 = new HashSet<Pokemon>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Movimientos> Movimientos { get; set; }
        public virtual ICollection<Pokemon> PokemonTipo1 { get; set; }
        public virtual ICollection<Pokemon> PokemonTipo2 { get; set; }
    }
}